Targets:
  target1:
    class: H
    value: 200

Weapons:
  AAA:
    AAA1:
      position: [10,11,12]
      missiles: 5
      prob_of_kill:
        target1: 0.8
      cost:
        target1: 300

  samsite:
    samsite1:
      position: [15,10,8]
      missiles: 3
      prob_of_kill:
        target1: 0.5

    samsite2:
      position: [20,31,51]
      missiles: 8
      prob_of_kill:
        target1: 0.8

  Jamers:
   jamer1:
    position: [11,12,23]
    range: 12
  
  AirBase: []
